apiVersion: apps/v1
kind: Deployment
metadata:
  name:  workshop-app
spec:
  selector:
    matchLabels:
      app:  workshop-app
  template:
    metadata:
      labels:
        app:  workshop-app
    spec:
      containers:
        - name:  workshop-app
          image: imageName # IMPORTANT: Update!
          imagePullPolicy: Always
          ports:
            - containerPort: 8096
              name: healthcheck
            - containerPort: 8086
              name: service
      imagePullSecrets:
        - name: artifactory-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  workshop-app
  name:  workshop-app
spec:
  type: LoadBalancer
  ports:
    - name: healthcheck
      port: 8096
      protocol: TCP
    - name: service
      port: 8086
      protocol: TCP
  selector:
    app:  workshop-app