apiVersion: apps/v1
kind: Deployment
metadata:
  name:  workshop-app
spec:
  selector:
    matchLabels:
      app:  workshop-app
  template:
    metadata:
      labels:
        app:  workshop-app
    spec:
      containers:
        - name:  workshop-app
          image: imageName # IMPORTANT: Update!
          env:
            - name: SERVICE_ENDPOINT
              value: "8086"
            - name: HEALTH_CHECK_ENDPOINT
              value: "80"
            - name: AUD
              value: "api.acme.com/test"
            - name: CID
              value: "0oa1emw7xmqeh4Spd5d7"
            - name: DOMAIN
              value: "dev-73225252.okta.com"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: healthcheck
            - containerPort: 8086
              name: service
      imagePullSecrets:
        - name: artifactory-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  workshop-app
  name:  workshop-app
spec:
  type: LoadBalancer
  ports:
    - name: healthcheck
      port: 80
      protocol: TCP
    - name: service
      port: 8086
      protocol: TCP
  selector:
    app:  workshop-app